[package]
name = "timelock_vault"
version = "0.1.0"
edition = "2021"

[lib]
name = "timelock_vault"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token", "associated_token"] }
