[package]
name = "compliance_wrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "compliance_wrapper"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token", "token-2022", "associated_token"] }
